# Gradle Properties
org.gradle.jvmargs = -Xmx3G
org.gradle.java.home = D:/jdk/jdk_25

# Source Options
use_modern_java_syntax = false
use_jetbrains_annotations = false

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

# Mod Information
mod_version = r1.1-61
root_package = com.meteor.extrabotany
mod_id = extrabotany
mod_name = ExtraBotany

# Mod Metadata (Optional)
mod_description = A Botania Addon adds some new flowers and miscs.
mod_url =
mod_update_json =
mod_authors = ExtraMeteorP
mod_credits =
mod_logo_path = assets/extrabotany/textures/logo.png

# Mapping Properties
mapping_channel = stable
mapping_version = 39
use_dependency_at_files = true

# Run Configurations
minecraft_username = XSmallWhiteX
extra_jvm_args =
extra_tweak_classes =

# Maven Publishing (Provide secret: MAVEN_USER, MAVEN_PASS)
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# Publishing
release_type = release
publish_with_changelog = ${{ it.file('CHANGELOG.md').exists() }}

# Publishing to CurseForge (Provide secret: CURSEFORGE_TOKEN)
publish_to_curseforge = false
curseforge_project_id =
curseforge_debug = false

# Publishing to Modrinth (Provide secret: MODRINTH_TOKEN)
publish_to_modrinth = false
modrinth_project_id =
modrinth_sync_readme = false
modrinth_debug = false

# If any properties changes below this line, refresh gradle again to ensure everything is working correctly.

# Modify Minecraft Sources
change_minecraft_sources = false

# Tags
use_tags = true
tag_class_name = ${root_package}.Tags

# Access Transformers
use_access_transformer = true
access_transformer_locations = META-INF/extrabotany_at.cfg

# Mixins
use_mixins = false
mixin_booter_version = 10.7
generate_mixins_json = true
mixin_configs = ${mod_id}
mixin_package = ${root_package}.mixin
mixin_refmap = mixins.${mod_id}.refmap.json

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
